sudo: required
services:
  - docker

  before_install:
  - docker build -t husan/docker-react -f Dockerfile.dev

  script:
  - docker run -e CI=true husan/docker-react npm run test -- -- coverage 